### ISSUE TITLE
Script is not loading (some error)

### ISSUE THREAD

**Issue by hafizio** [PostCo/postco-shopify#37]
Failed to load resource: net::ERR_CONNECTION_RESET

**Comment by andychong1996** [comment]
- Not super sure what is the exact error.
- The only error traceable is from the plugin side, around 11.18am on 16 Jun 2017: https://app.timber.io/organizations/postco/apps/postco-plugin-production/console?filters=level%3Aerror
- Suspected error source: rawgit, maybe consider host it on AWS S3.
